name: Release RP 
on:
  push:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Main Branch
      uses: actions/checkout@v2
    - name: Zip Folder
      uses: vimtor/action-zip@v1
      with:
        files: assets pack.mcmeta pack.png
        dest: result.zip
    - name: Bump version and push tag
      uses: anothrNick/github-tag-action@master
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        REPO_OWNER: kyrkis   
    - name: Create Release
      uses: ncipollo/release-action@v1
      with: 
       artifacts: "result.zip"
    
