name: Release RP 
on:
  push:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Main Branch
      uses: actions/checkout@v2
    - name: Zip Folder
      uses: vimtor/action-zip@v1
      with:
        files: assets pack.mcmeta pack.png
        dest: result.zip
    - name: Create Release
      uses: ncipollo/release-action@v1
      with: 
       artifacts: "resutl.zip"
    
