name: Release RP 
on: workflow_dispatch
    
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Main Branch
      uses: actions/checkout@v2
    - name: Bump version and push tag
      uses: anothrNick/github-tag-action@master
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        REPO_OWNER: Gamemode4Dev
    - name: Get Previous tag
      id: previoustag
      uses: "WyriHaximus/github-action-get-previous-tag@v1"
    - name: Update pack.mcmeta version field
      uses: jossef/action-set-json-field@v2.1
      with:
        file: pack.mcmeta
        field: version
        value: ${{ steps.previoustag.outputs.tag }}
    - name: Zip Folder
      uses: vimtor/action-zip@v1
      with:
        files: assets/ pack.mcmeta pack.png overlay_22
        recursive: false
        dest: Evergrowth_RP.zip
    - name: Create Release
      uses: ncipollo/release-action@v1
      with: 
       artifacts: "Evergrowth_RP.zip"
       tag: ${{ steps.previoustag.outputs.tag }}
    
