name: Release RP 
on:
  push:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Main Branch
      uses: actions/checkout@v2
    - name: Bump version and push tag
      uses: anothrNick/github-tag-action@master
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        REPO_OWNER: kyrkis
    - name: Get Previous tag
      id: previoustag
      uses: "WyriHaximus/github-action-get-previous-tag@v1"
    - name: Zip Folder
      uses: vimtor/action-zip@v1v
      with:
        files: assets/ pack.mcmeta pack.png
        dest: Puzzle_Boxes_RP-${{ steps.previoustag.outputs.tag }}.zip
        recursive: true  
    - name: Create Release
      uses: ncipollo/release-action@v1
      with: 
       artifacts: "Puzzle_Boxes_RP-${{ steps.previoustag.outputs.tag }}.zip"
       tag: ${{ steps.previoustag.outputs.tag }}
    
